### ISSUE TITLE
TypeError: Object #<PouchDB> has no method 'getUrl'

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/pouchdb-authentication#44]
Is it possible that there used to be a `db.getUrl()` method, which recently has been removed, but you still use it in this plugin? 

```
TypeError: Object #<PouchDB> has no method 'getUrl'
    at getBaseUrl (.../node_modules/pouchdb-authentication/lib/utils.js:6:13)
    at Object.exports.getSessionUrl (.../node_modules/pouchdb-authentication/lib/utils.js:12:10)
    at PouchDB.<anonymous> (.../node_modules/pouchdb-authentication/lib/index.js:113:19)
    at .../node_modules/pouchdb-authentication/lib/utils.js:65:14
    at tryCatch2 (.../node_modules/pouchdb-authentication/node_modules/pouchdb/node_modules/bluebird/js/main/util.js:73:19)
    at Promise$_resolveFromResolver [as _resolveFromResolver] (.../node_modules/pouchdb-authentication/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:595:13)
    at new Promise (.../node_modules/pouchdb-authentication/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:87:37)
    at PouchDB.<anonymous> (.../node_modules/pouchdb-authentication/lib/utils.js:53:19)
    at PouchDB.getSession (.../node_modules/pouchdb-authentication/lib/utils.js:34:16)
```

**Comment by gr2m** [comment]
okay, it's all my fault, I had a bug and I `new PouchDB('http://localhost:5984/_users')` was `new PouchDB('_users')`

Sorry for the noise :)

**Comment by jgillich** [comment]
Another one here, called it on the local db by mistake. However, the other methods actually handle that with a proper error, maybe this one should too? @nolanlawson

**Comment by nolanlawson** [comment]
Yep, I'd be happy to accept a PR to make it so `.getSession()` throws an error if you try to do it on a local database. :)
